requires 'WWW::Telegram::BotAPI';
requires 'Mojo::IOLoop';
requires 'Mojo::IOLoop::ReadWriteProcess';
requires 'Mojo::JSON';
requires 'Mojo::File';
requires 'Twitter::API';
requires 'Text::SimpleTable::AutoWidth';
requires 'Getopt::Long';

on 'test' => sub {
    requires 'Perl::Critic::Freenode';
    requires 'Perl::Critic';
    requires 'Perl::Tidy';
    requires 'Test::More';
    requires 'Test::Mojo';
};
