requires 'WWW::Telegram::BotAPI';
requires 'Mojo::IOLoop';
requires 'Mojo::IOLoop::ReadWriteProcess';
requires 'Mojo::JSON';
requires 'Mojo::File';
requires 'Test::More';
requires 'Twitter::API';
requires 'Text::SimpleTable::AutoWidth';
